on:
  push:
    branches:
    - main
env:
  CONTAINER_REGISTRY_LOGIN_SERVER: webapplication120231021195737.azurecr.io
  PROJECT_NAME_FOR_DOCKER: webapplication1
  CONTAINER_APP_NAME: app01
  CONTAINER_APP_RESOURCE_GROUP_NAME: win11rg
  CONTAINER_APP_CONTAINER_NAME: app01
jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.WebApplication120231021195737_USERNAME_CC8B }}
        password: ${{ secrets.WebApplication120231021195737_PASSWORD_CC8B }}
    - name: Build and push Docker image to Azure container registry
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
        file: ${{ env.PROJECT_NAME_FOR_DOCKER }}
  deploy:
    runs-on: ubuntu-latest
    needs: buildImage
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.app01_SPN }}
    - name: Deploy to Azure container app
      uses: azure/CLI@v1
      with:
        inlineScript: >-
          az config set extension.use_dynamic_install=yes_without_prompt

          az containerapp registry set --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --server ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }} --username ${{ secrets.WebApplication120231021195737_USERNAME_CC8B }} --password ${{ secrets.WebApplication120231021195737_PASSWORD_CC8B }}

          az containerapp update --name ${{ env.CONTAINER_APP_NAME }} --container-name ${{ env.CONTAINER_APP_CONTAINER_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --image ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
    - name: Azure logout
      run: az logout
